const getRandomInt = require('../common/randomInt')

module.exports = {
  subDistrictList: [
    'ศรีภูมิ',
    'พระสิงห์',
    'หายยา',
    'ช้างม่อย',
    'ช้างคลาน',
    'วัดเกต',
    'ช้างเผือก',
    'สุเทพ',
    'แม่เหียะ',
    'ป่าแดด',
    'หนองหอย',
    'ท่าศาลา',
    'หนองป่าครั่ง',
    'ฟ้าฮ่าม',
    'ป่าตัน',
    'สันผีเสื้อ',
  ],
  cafeNames: [
    "บ้านกาแฟ", 
    "มุมกาแฟ", 
    "ร้านกาแฟใจดี", 
    "ร้านกาแฟหลังบ้าน", 
    "ร้านกาแฟใต้ต้นไม้", 
    "ร้านกาแฟริมทาง", 
    "ร้านกาแฟบรรยากาศดี", 
    "ร้านกาแฟของคนรักกาแฟ", 
    "ร้านกาแฟสำหรับคนนอนดึก", 
    "ร้านกาแฟสำหรับคนทำงาน", 
  
    "ร้านกาแฟและของหวาน", 
    "ร้านกาแฟและหนังสือ", 
    "ร้านกาแฟและแมว", 
    "ร้านกาแฟและสุนัข", 
    "ร้านกาแฟและงานฝีมือ", 
    "ร้านกาแฟและดนตรีสด", 
    "ร้านกาแฟและวิวสวย", 
    "ร้านกาแฟและห้องสมุด", 
    "ร้านกาแฟและพื้นที่ทำงาน", 
    "ร้านกาแฟและกิจกรรมต่างๆ", 
  
    "ชีวิตดี๊ดีกาแฟ", 
    "สุขใจกาแฟ", 
    "อบอุ่นกาแฟ", 
    "ผ่อนคลายกาแฟ", 
    "สบายใจกาแฟ", 
    "รื่นรมย์กาแฟ", 
    "ฟินฟินกาแฟ", 
    "อร่อยสุดสุดกาแฟ", 
    "หอมกรุ่นกาแฟ", 
    "กลมกล่อมกาแฟ", 
  
    "มุมโปรดคาเฟ่", 
    "บ้านหลังที่สอง", 
    "ที่พักผ่อนคาเฟ่", 
    "พื้นที่ส่วนตัวกาแฟ", 
    "โลกส่วนตัวคาเฟ่", 
    "รังนกคาเฟ่", 
    "ช่องว่างกาแฟ", 
    "ช่วงเวลาคาเฟ่", 
    "พักก่อน คาเฟ่", 
    "ผ่อนคลายคาเฟ่", 
   
    "Coffee Home",
    "Coffee Corner",
    "Good Day Cafe",
    "Backyard Coffee",
    "Under the Tree Cafe",
    "By the Road Cafe",
    "Good Atmosphere Cafe",
    "Coffee for Coffee Lovers",
    "Cafe for Night Owls",
    "Cafe for Workers",
  
    "Coffee and Desserts",
    "Coffee and Books",
    "Coffee and Cats",
    "Coffee and Dogs",
    "Coffee and Crafts",
    "Coffee and Live Music",
    "Coffee and Beautiful Views",
    "Coffee and Library",
    "Coffee and Workspace",
    "Coffee and Activities",
  
    "Favorite Corner",
    "Second Home",
    "Place to Relax",
    "Personal Space",
    "Private World",
    "Bird's Nest",

    "Bean Spot",
    "Coffee Cove",
    "Brew House",
    "Java Hut",
    "Cuppa Cafe",
    "Espresso Place",
    "Brew Spot",
    "Bean Bar",
    "Coffee Nook",
    "The Roast",
    "Brew Cafe",
    "Java House",
    "Cup & Bean",
    "Bean Café",
    "Espresso Spot",
    "Coffee Stop",
    "Brew Hub",
    "Java Spot",
    "Cup O' Joe",
    "Bean Joint",
    "The Roastery",
    "Brew Stop",
    "Coffee Den",
    "Bean Corner",
    "Espresso Bar",
    "Java Stop",
    "Cuppa Spot",
    "Bean Stop",
    "Brew Joint",
    "Coffee Haven",
    "Java Nook",
    "Cup & Brew",
    "Bean Depot",
    "Brew Corner",
    "Espresso Hub",
    "Coffee Hub",
    "Java Haven",
    "Cuppa House",
    "Bean Shack",
    "Brew Shack",
    "Coffee Lounge",
    "Java Lounge",
    "Bean Lounge",
    "Brew Lounge",
    "Cuppa Lounge",
    "Espresso Lounge",
    "Coffee House",
    "Java House",
    "Bean House",
    "Brew House",
    "Cuppa House",
    "Coffee Place",
    "Java Place",
    "Bean Place",
    "Brew Place",
    "Cuppa Place",
    "Espresso Place",
    "Coffee Cabin",
    "Java Cabin",
    "Bean Cabin",
    "Brew Cabin",
    "Cuppa Cabin",
    "Espresso Cabin",
    "Coffee Club",
    "Java Club",
    "Bean Club",
    "Brew Club",
    "Cuppa Club",
    "Espresso Club",
    "Coffee Cove",
    "Java Cove",
    "Bean Cove",
    "Brew Cove",
    "Cuppa Cove",
    "Espresso Cove",
    "Coffee Corner",
    "Java Corner",
    "Bean Corner",
    "Brew Corner",
    "Cuppa Corner",
    "Espresso Corner",
    "Coffee Court",
    "Java Court",
    "Bean Court",
    "Brew Court",
    "Cuppa Court",
    "Espresso Court",
    "Coffee Base",
    "Java Base",
    "Bean Base",
    "Brew Base",
    "Cuppa Base",
    "Espresso Base",
    "Coffee Den",
    "Java Den",
    "Bean Den",
    "Brew Den",
    "Cuppa Den",
    "Espresso Den",
    "Coffee Drip",
    "Java Drip"
  ],
  coffeeShopDescriptions: (name) => {
    const descriptions = [
      `Welcome to ${name}, where every cup tells a story. Enjoy freshly brewed coffee in a cozy atmosphere perfect for catching up with friends or diving into a good book.`,
      `At ${name}, we're passionate about serving the perfect cup of joe. Whether you're in need of a morning boost or a midday pick-me-up, we've got you covered with our selection of premium coffees.`,
      `Step into ${name} and let the aroma of freshly ground beans awaken your senses. With comfortable seating and friendly service, it's the ideal spot to relax and recharge.`,
      `${name} is your neighborhood coffee destination, where quality meets convenience. Swing by for a quick caffeine fix or stay awhile and soak in the laid-back vibe.`,
      `${name} offers a warm and inviting atmosphere paired with delicious coffee crafted with care. Join us for a cup of comfort and a moment of tranquility.`,
      `${name} is where coffee dreams come true. From velvety lattes to rich espressos, each sip is a journey of flavor crafted just for you.`,
      `${name} is more than just a coffee shop it's a community hub where locals gather to connect over their love of great coffee and good conversation.`,
      `${name}is the perfect blend of simplicity and sophistication. Indulge in our handcrafted beverages while basking in the relaxed ambiance at ${name}.`,
      `${name} is your cozy corner of caffeine heaven. Whether you're flying solo or meeting up with friends, you'll always feel at home here at ${name}.`,
      `${name} is where passion meets perfection. With a commitment to quality and a dedication to delighting our customers, every cup is crafted with love at ${name}.`
    ]
    return descriptions[getRandomInt(0, descriptions.length)]
  },
  sampleCoverImages: [
    'https://media-cdn.tripadvisor.com/media/photo-s/1b/3f/c1/f1/kj-coffee-shop-es-un.jpg',
    'https://sumatocoffee.com/cdn/shop/articles/coffee_3839f67b-f767-4937-baac-bf300773bdac_900x.jpg?v=1677124219',
    'https://www.barniescoffee.com/cdn/shop/articles/bar-1869656_1920.jpg?v=1660683986',
    'https://i.pinimg.com/originals/36/66/a4/3666a417a3a5078c5ef5c7672bc13433.jpg',
    'https://media-cdn.tripadvisor.com/media/photo-s/1a/2b/ea/41/photo0jpg.jpg',
    'https://images.edrawmax.com/article2023/coffee-shop-org-chart/organizational-structure-of-coffee-shop.jpg',
    'https://www.posist.com/restaurant-times/wp-content/uploads/2023/07/How-To-Start-A-Coffee-Shop-Business-A-Complete-Guide.jpg'
  ]

}