module.exports = {
  subDistrictList: [
    'ศรีภูมิ',
    'พระสิงห์',
    'หายยา',
    'ช้างม่อย',
    'ช้างคลาน',
    'วัดเกต',
    'ช้างเผือก',
    'สุเทพ',
    'แม่เหียะ',
    'ป่าแดด',
    'หนองหอย',
    'ท่าศาลา',
    'หนองป่าครั่ง',
    'ฟ้าฮ่าม',
    'ป่าตัน',
    'สันผีเสื้อ',
  ],

  cafeNames: [
    "บ้านกาแฟ", 
    "มุมกาแฟ", 
    "ร้านกาแฟใจดี", 
    "ร้านกาแฟหลังบ้าน", 
    "ร้านกาแฟใต้ต้นไม้", 
    "ร้านกาแฟริมทาง", 
    "ร้านกาแฟบรรยากาศดี", 
    "ร้านกาแฟของคนรักกาแฟ", 
    "ร้านกาแฟสำหรับคนนอนดึก", 
    "ร้านกาแฟสำหรับคนทำงาน", 
  
    "ร้านกาแฟและของหวาน", 
    "ร้านกาแฟและหนังสือ", 
    "ร้านกาแฟและแมว", 
    "ร้านกาแฟและสุนัข", 
    "ร้านกาแฟและงานฝีมือ", 
    "ร้านกาแฟและดนตรีสด", 
    "ร้านกาแฟและวิวสวย", 
    "ร้านกาแฟและห้องสมุด", 
    "ร้านกาแฟและพื้นที่ทำงาน", 
    "ร้านกาแฟและกิจกรรมต่างๆ", 
  
    "ชีวิตดี๊ดีกาแฟ", 
    "สุขใจกาแฟ", 
    "อบอุ่นกาแฟ", 
    "ผ่อนคลายกาแฟ", 
    "สบายใจกาแฟ", 
    "รื่นรมย์กาแฟ", 
    "ฟินฟินกาแฟ", 
    "อร่อยสุดสุดกาแฟ", 
    "หอมกรุ่นกาแฟ", 
    "กลมกล่อมกาแฟ", 
  
    "มุมโปรดคาเฟ่", 
    "บ้านหลังที่สอง", 
    "ที่พักผ่อนคาเฟ่", 
    "พื้นที่ส่วนตัวกาแฟ", 
    "โลกส่วนตัวคาเฟ่", 
    "รังนกคาเฟ่", 
    "ช่องว่างกาแฟ", 
    "ช่วงเวลาคาเฟ่", 
    "พักก่อน คาเฟ่", 
    "ผ่อนคลายคาเฟ่", 
   
    "Coffee Home",
    "Coffee Corner",
    "Good Day Cafe",
    "Backyard Coffee",
    "Under the Tree Cafe",
    "By the Road Cafe",
    "Good Atmosphere Cafe",
    "Coffee for Coffee Lovers",
    "Cafe for Night Owls",
    "Cafe for Workers",
  
    "Coffee and Desserts",
    "Coffee and Books",
    "Coffee and Cats",
    "Coffee and Dogs",
    "Coffee and Crafts",
    "Coffee and Live Music",
    "Coffee and Beautiful Views",
    "Coffee and Library",
    "Coffee and Workspace",
    "Coffee and Activities",
  
    "Favorite Corner",
    "Second Home",
    "Place to Relax",
    "Personal Space",
    "Private World",
    "Bird's Nest",

    "Bean Spot",
    "Coffee Cove",
    "Brew House",
    "Java Hut",
    "Cuppa Cafe",
    "Espresso Place",
    "Brew Spot",
    "Bean Bar",
    "Coffee Nook",
    "The Roast",
    "Brew Cafe",
    "Java House",
    "Cup & Bean",
    "Bean Café",
    "Espresso Spot",
    "Coffee Stop",
    "Brew Hub",
    "Java Spot",
    "Cup O' Joe",
    "Bean Joint",
    "The Roastery",
    "Brew Stop",
    "Coffee Den",
    "Bean Corner",
    "Espresso Bar",
    "Java Stop",
    "Cuppa Spot",
    "Bean Stop",
    "Brew Joint",
    "Coffee Haven",
    "Java Nook",
    "Cup & Brew",
    "Bean Depot",
    "Brew Corner",
    "Espresso Hub",
    "Coffee Hub",
    "Java Haven",
    "Cuppa House",
    "Bean Shack",
    "Brew Shack",
    "Coffee Lounge",
    "Java Lounge",
    "Bean Lounge",
    "Brew Lounge",
    "Cuppa Lounge",
    "Espresso Lounge",
    "Coffee House",
    "Java House",
    "Bean House",
    "Brew House",
    "Cuppa House",
    "Coffee Place",
    "Java Place",
    "Bean Place",
    "Brew Place",
    "Cuppa Place",
    "Espresso Place",
    "Coffee Cabin",
    "Java Cabin",
    "Bean Cabin",
    "Brew Cabin",
    "Cuppa Cabin",
    "Espresso Cabin",
    "Coffee Club",
    "Java Club",
    "Bean Club",
    "Brew Club",
    "Cuppa Club",
    "Espresso Club",
    "Coffee Cove",
    "Java Cove",
    "Bean Cove",
    "Brew Cove",
    "Cuppa Cove",
    "Espresso Cove",
    "Coffee Corner",
    "Java Corner",
    "Bean Corner",
    "Brew Corner",
    "Cuppa Corner",
    "Espresso Corner",
    "Coffee Court",
    "Java Court",
    "Bean Court",
    "Brew Court",
    "Cuppa Court",
    "Espresso Court",
    "Coffee Base",
    "Java Base",
    "Bean Base",
    "Brew Base",
    "Cuppa Base",
    "Espresso Base",
    "Coffee Den",
    "Java Den",
    "Bean Den",
    "Brew Den",
    "Cuppa Den",
    "Espresso Den",
    "Coffee Drip",
    "Java Drip"
  ],
}