version: '3.8'
services:
  
  rcmd-mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27019:27017
    volumes:
      - ./mongodata/recommendation:/data/db

  rcmd-node:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - APP_PORT=3001
      - MONGO_URI=mongodb://rcmd-mongo:27017
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASENAME=recommendation
    ports:
      - 3001:3001
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
    depends_on:
      - rcmd-mongo
  
networks:
    cafe-microservice:
      external: true
