version: '3'
services:

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=123456 
    volumes:
      - ./db:/data/db

  backend:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - APP_PORT=4000
    ports:
      - 4000:4000
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
    depends_on:
      - mongo
