version: '3.8'
services:
  
  promotion-mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27020:27017
    volumes:
      - ./mongodata/promotion:/data/db

  promotion-node:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - APP_PORT=3003
      - MONGO_URI=mongodb://promotion-mongo:27017
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASENAME=promotion
    ports:
      - 3003:3003
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
    depends_on:
      - promotion-mongo
  
networks:
    default:
        external:
            name: cafemicroservicenetwork
