version: '3.8'
services:

  analytic-mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - ./mongodata/analytic:/data/db
  
  analytic-node:
    image: node:alpine
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - APP_PORT=3000
      - MONGO_URI=mongodb://analytic-mongo:27017
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - DB_DATABASENAME=analytic 
    ports:
      - 3000:3000
    command: ['/bin/sh', '-c', 'yarn && yarn dev']
    depends_on:
      - analytic-mongo
  
networks:
    default:
        external:
            name: cafemicroservicenetwork